image:
  quay.io/python-devs/ci-image:master

before_script:
  - python3 -m venv env
  - source ./env/bin/activate
  - python -m pip install beautifulsoup4 selenium pandas

stages:
  - test

test:
  stage: test
  script:
    - python3 -m gml
