image:
  python:3.7

before_script:
  - apt-get install -y software-properties-common
  - apt-get update -y
  - add-apt-repository ppa:mozillateam/ppa
  - apt-get update -y
  - apt-get install -y firefox
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzvf geckodriver-v0.26.0-linux64.tar.gz
  - rm geckodriver-v0.26.0-linux64.tar.gz
  - mv geckodriver /usr/local/bin
  - python3 --version
  - python3 -m venv env
  - source ./env/bin/activate
  - python -m pip install beautifulsoup4 selenium pandas

stages:
  - test

test:
  stage: test
  script:
    - python3 -m gml
