image:
  python:3.7

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y firefox-esr
  - chmod +x ./install.sh
  - ./install.sh

stages:
  - test

test:
  stage: test
  script:
    - printf "2\n1\n2\n" | python3 gml.py --arg myArg.
