image:
  python:3.7

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install -y firefox-esr
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar -xzvf geckodriver-v0.26.0-linux64.tar.gz
  - rm geckodriver-v0.26.0-linux64.tar.gz
  - mv geckodriver /usr/local/bin
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - rm phantomjs-2.1.1-linux-x86_64.tar.bz2
  - mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
  - python3 --version
  - python3 -m venv env
  - source ./env/bin/activate
  - python -m pip install beautifulsoup4 selenium pandas

stages:
  - test

test:
  stage: test
  script:
    - python3 -m gml
